version: 0.2
phases:
  build:
    commands:
      - sam package --template-file template.yaml --s3-bucket todo-nn --output-template-file packaged-template.yaml
artifacts:
  files:
    - packaged-template.yaml
